import { StyleSheet } from "react-native";

import type { ThemeColors } from "./theme";

export function createPostStyles(colors: ThemeColors) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    content: {
      padding: 16,
      paddingBottom: 32,
      gap: 16,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 12,
    },
    kicker: {
      fontSize: 14,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.4,
      color: colors.tabActive,
      marginBottom: 6,
    },
    title: {
      fontSize: 28,
      fontWeight: "700",
      color: colors.text,
    },
    subtitle: {
      marginTop: 6,
      fontSize: 15,
      lineHeight: 22,
      color: colors.mutedText,
      maxWidth: 300,
    },
    headerBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    headerBadgeText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.text,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      gap: 14,
    },
    authorRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    avatar: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: colors.tabActive,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarText: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.surface,
    },
    authorMeta: {
      flex: 1,
      gap: 4,
    },
    authorName: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text,
    },
    authorAudience: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    authorAudienceText: {
      fontSize: 13,
      color: colors.mutedText,
    },
    fakeTextArea: {
      minHeight: 170,
      borderRadius: 18,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      gap: 10,
    },
    textAreaPrompt: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.text,
    },
    textAreaBody: {
      fontSize: 15,
      lineHeight: 24,
      color: colors.mutedText,
    },
    optionRow: {
      flexDirection: "row",
      gap: 10,
      flexWrap: "wrap",
    },
    optionChip: {
      minHeight: 40,
      paddingHorizontal: 12,
      borderRadius: 999,
      backgroundColor: colors.background,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
    },
    optionChipText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.text,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.text,
    },
    stack: {
      gap: 10,
    },
    rowCard: {
      minHeight: 64,
      borderRadius: 16,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    rowCardLeft: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    selectionDot: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
    selectionDotInner: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.tabActive,
    },
    rowTitle: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.text,
    },
    rowDetail: {
      fontSize: 13,
      color: colors.mutedText,
      marginTop: 2,
    },
    placeholderGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
    },
    placeholderTile: {
      width: "47%",
      minHeight: 88,
      borderRadius: 16,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      padding: 12,
    },
    placeholderTileText: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.text,
      textAlign: "center",
    },
    previewCard: {
      borderRadius: 18,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      gap: 12,
    },
    previewTopRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    previewAvatar: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    previewAvatarText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
    },
    previewMeta: {
      gap: 2,
    },
    previewName: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.text,
    },
    previewRole: {
      fontSize: 12,
      color: colors.mutedText,
    },
    previewContent: {
      fontSize: 14,
      lineHeight: 22,
      color: colors.text,
    },
    previewFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    previewStat: {
      fontSize: 12,
      color: colors.mutedText,
    },
    actionRow: {
      flexDirection: "row",
      gap: 10,
    },
    secondaryButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    secondaryButtonText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
    },
    primaryButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 14,
      backgroundColor: colors.tabActive,
      alignItems: "center",
      justifyContent: "center",
    },
    primaryButtonText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.surface,
    },
  });
}
